spring:
  application:
    name: acpCw2Service


info:
  app:
    name: ACP CW2
    description: Simple ACP CW2 service
    version: 0.0.3

management:
  endpoints:
    web:
      exposure:
        include: info, health, env
  info:
    env:
      enabled: true

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
server:
  port: 8080

logging:
  level:
    root: WARN
    uk.ac.ed.acp.cw2: INFO
    uk.ac.ed.acp.cw2.domain: INFO
    uk.ac.ed.acp.cw2.service.CacheService: INFO
    org.springframework: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{20} - %msg%n"

